extends:
  - stylelint-config-standard
customSyntax: postcss-scss
rules:
  at-rule-no-unknown: null
  declaration-property-value-no-unknown: null
  selector-class-pattern: ^([a-z][a-z0-9]*(?:-[a-z0-9]+)*(?:__[a-z0-9]+(?:-[a-z0-9]+)*)?(?:--[a-z0-9]+(?:-[a-z0-9]+)*)?)$
